dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: nodejs-hello-world-2
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: nodejs-hello-world-4
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
